# Part IA Computing: Michaelmas Term
## Exercises 07.1, 07.2, 07.3 and 07.4

Edwin Bahrami Balani ([`eb677`](mailto:eb677@cam.ac.uk))

In [1]:
# Part IA Computing: Michaelmas Term
# Edwin Bahrami Balani (eb677@cam.ac.uk)

# Exercises 07.1, 07.2, 07.3 and 07.4
import numpy as np

In [2]:
type(np.array([]))

numpy.ndarray

> ## Exercise 07.1 (indexing and timing)
> 
> Create two very long NumPy arrays `x` and `y` and sum the arrays using:
> 
> 1. The NumPy addition syntax, `z = x + y`; and
> 2. A `for` loop that computes the sum entry-by-entry
> 
> Compare the time required for the two approaches for vectors of different lengths. The values of the array entries are not important for this test.
> 
> *Hint:* To loop over an array using indices, try a construction like:
> ```python
> x = np.ones(100)
> y = np.ones(len(x))
> for i in range(len(x)):
>     print(x[i]*y[i])
> ```

In [3]:
# Part IA Computing: Michaelmas Term
# Edwin Bahrami Balani (eb677@cam.ac.uk)

# Exercise 07.1
import numpy as np

x = np.linspace(0, 238746, 1000)
y = np.linspace(287652, 28642, 1000)
%timeit z1 = x + y

def sum_array(x, y):
    z = np.empty([len(x), 1])
    for i in range(len(x)):
        z[i] = x[i] + y[i]
    return z
%timeit z2 = sum_array(x, y)

The slowest run took 8.66 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.14 µs per loop
1000 loops, best of 3: 547 µs per loop


> ## Exercise 07.2 (member functions and slicing)
> 
> Anonymised scores (out of 60) for an examination are stored in a NumPy array. Write:
> 
> 1. A function that takes a NumPy array of the raw scores and returns the scores as a percentage sorted from 
>    lowest to highest (try using `scores.sort()`, where `scores` is an Numpy array).
> 1. A function that returns the maximum, minimum and mean of the raw scores as a dictionary with the 
>    keys '`min`', '`max`' and '`mean`'. Use the NumPy array functions `min()`, `max()` and `mean()` to do the 
>    computation, e.g. `max = scores.max()`.
> 1. Modify your function for the min, max and mean to optionally exclude the highest and lowest scores from the 
>    computation of the min, max and mean. *Hint:* sort the array of scores and use array slicing to exclude
>    the first and the last entries.
> 
> Use the scores 
> ```python
> scores = np.array([58.0, 35.0, 24.0, 42, 7.8])
> ```
> to test your functions.

In [4]:
# Part IA Computing: Michaelmas Term
# Edwin Bahrami Balani (eb677@cam.ac.uk)

# Exercise 07.2
import numpy as np

to_percentages = lambda ar: np.sort(ar)/60*100
stats = lambda ar: {'min':ar.min(), 'max':ar.max(), 'mean':ar.mean()}
stats_slice = lambda ar: stats(np.sort(ar)[1:-1])

scores = np.array([58.0, 35.0, 24.0, 42, 7.8])

print(to_percentages(scores))
print(stats(scores))
print(stats_slice(scores))

[ 13.          40.          58.33333333  70.          96.66666667]
{'max': 58.0, 'mean': 33.359999999999999, 'min': 7.7999999999999998}
{'max': 42.0, 'mean': 33.666666666666664, 'min': 24.0}


> ## Exercise 07.3 (slicing)
> 
> For the two-dimensional array

In [5]:
A = np.array([[4.0, 7.0, -2.43, 67.1],
             [-4.0, 64.0, 54.7, -3.33],
             [2.43, 23.2, 3.64, 4.11],
             [1.2, 2.5, -113.2, 323.22]])
print(A)

[[   4.      7.     -2.43   67.1 ]
 [  -4.     64.     54.7    -3.33]
 [   2.43   23.2     3.64    4.11]
 [   1.2     2.5  -113.2   323.22]]


> use array slicing to
> 
> 1. Extract the third column as a 1D array
> 2. Extract the first two rows as a 2D sub-array
> 3. Extract the bottom-right $2 \times 2$ block as a 2D sub-array
> 4. Compute the tranpose of `A` (search online to find the syntax for how to do this)
> 5. Sum the last column of `A`
> 
> Print the results to the screen to check. Try to use array slicing such that your code would still work if the dimensions of `A` were enlarged.

In [6]:
# Part IA Computing: Michaelmas Term
# Edwin Bahrami Balani (eb677@cam.ac.uk)

# Exercise 07.3
import numpy as np

A = np.array([[4.0, 7.0, -2.43, 67.1],
             [-4.0, 64.0, 54.7, -3.33],
             [2.43, 23.2, 3.64, 4.11],
             [1.2, 2.5, -113.2, 323.22]])
print(A)
print()

print("Third column")
print(A[:,2])
print()

print("First two rows")
print(A[0:2])
print()

print("Bottom 2x2 corner")
print(A[2:4,2:4])
print()

print("Sum of last column")
print(sum(A[:,3]))

[[   4.      7.     -2.43   67.1 ]
 [  -4.     64.     54.7    -3.33]
 [   2.43   23.2     3.64    4.11]
 [   1.2     2.5  -113.2   323.22]]

Third column
[  -2.43   54.7     3.64 -113.2 ]

First two rows
[[  4.     7.    -2.43  67.1 ]
 [ -4.    64.    54.7   -3.33]]

Bottom 2x2 corner
[[   3.64    4.11]
 [-113.2   323.22]]

Sum of last column
391.1


> ## Exercise 07.4 (optional extension)
> 
>In a previous exercise you implemented the bisection algorithm to find approximate roots of a mathematical function. Use the SciPy bisection function `optimize.bisect` (http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.optimize.bisect.html) to find roots of the mathematical function that was used in the previous exercise. Compare the results computed by SciPy and your program from the earlier exercise, and compare the computational time (using `%time`).

In [7]:
# Part IA Computing: Michaelmas Term
# Edwin Bahrami Balani (eb677@cam.ac.uk)

# Exercise 07.4
import numpy as np
from scipy import optimize

def compute_root(f, x0, x1, tol, max_it):
    """Finds a root of function f(x) between x=x0 and x=x1 using bisection"""
    i = 0
    xmid = (x0+x1)/2
    fmid = f(xmid)
    while (abs(fmid) >= tol) and (i < max_it):
        i += 1
        xmid = (x0+x1)/2
        fmid = f(xmid)
        if (fmid * f(x0) < 0):
            x1 = xmid
        else:
            x0 = xmid
    return xmid, fmid, i

def root_recur(f, x0, x1, tol, rec_count=1):
    """Recursive bisection-method root finding function for x in [x0, x1]"""
    xmid = (x0+x1)/2
    fmid = f(xmid)
    if abs(fmid) < tol:
        return xmid, fmid, rec_count
    if (fmid * f(x0) < 0):
        return(root_recur(f, x0, xmid, tol, rec_count+1))
    else:
        return(root_recur(f, xmid, x1, tol, rec_count+1))
    

f = lambda x: x**3 - 6*(x**2) + 4*x + 12
g = lambda x: 7*(x**2) - 5*x - 12 # roots are x = -1, x = 12/7 = 1.714

print("Using compute_root")
%timeit x = compute_root(f, 3, 6, 1e-6, 1000)
%timeit x = compute_root(g, 1, 4, 1e-8, 1000)
print()

print("Using root_recur")
%timeit x = root_recur  (f, 3, 6, 1e-6)
%timeit x = root_recur  (g, 1, 4, 1e-8)
print()

print("Using scipy.optimize.bisect")
%timeit x = optimize.bisect(f, 3, 6, xtol=1e-6, maxiter=1000)
%timeit x = optimize.bisect(g, 1, 4, xtol=1e-8, maxiter=1000)

Using compute_root
10000 loops, best of 3: 42.4 µs per loop
10000 loops, best of 3: 43.3 µs per loop

Using root_recur
10000 loops, best of 3: 42.5 µs per loop
10000 loops, best of 3: 44.9 µs per loop

Using scipy.optimize.bisect
100000 loops, best of 3: 20.3 µs per loop
100000 loops, best of 3: 18.7 µs per loop
